apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timesheet-agent
  namespace: argocd
spec:
  project: hr-ai
  source:
    repoURL: https://github.com/tanloc-98/demo-scale-ai.git
    targetRevision: HEAD
    path: k8s/agents
    directory:
      include: "timesheet-*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: hr-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
